name: unforge

on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string
      proof:
        required: true
        type: string

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: carllaliberte/unforge-check@v1.0.0
        with:
          file: ${{ inputs.file }}
          proof: ${{ inputs.proof }}
